dataRefTransform:
  namespaced: false

cellIdPreamble: "cell-"

cells:
  porta1:
    datapoint: "last"
    dataRef: "porta1"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta2:
    datapoint: "last"
    dataRef: "porta2"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta3:
    datapoint: "last"
    dataRef: "porta3"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta4:
    datapoint: "last"
    dataRef: "porta4"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta5:
    datapoint: "last"
    dataRef: "porta5"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta6:
    datapoint: "last"
    dataRef: "porta6"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta7:
    datapoint: "last"
    dataRef: "porta7"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta8:
    datapoint: "last"
    dataRef: "porta8"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta9:
    datapoint: "last"
    dataRef: "porta9"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta10:
    datapoint: "last"
    dataRef: "porta10"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta11:
    datapoint: "last"
    dataRef: "porta11"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta12:
    datapoint: "last"
    dataRef: "porta12"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta13:
    datapoint: "last"
    dataRef: "porta13"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta14:
    datapoint: "last"
    dataRef: "porta14"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta15:
    datapoint: "last"
    dataRef: "porta15"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  porta16:
    datapoint: "last"
    dataRef: "porta16"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}
  power:
    datapoint: "last"
    dataRef: "power"
    labelColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "green", level: 1}
        - {color: "red", level: 2}