dataRefTransform:
  namespaced: false

cellIdPreamble: "cell-"

cells:
  porta1:
    datapoint: "last"
    dataRef: "Interface Gi0/1(PHFWNG01): Operational status"
    fillColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "green", level: 1}
    label:
      valueMap:
        0: "Down"
        1: "Up"