anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"

datapoint: "last"

cellIdPreamble: "cell-"
dataRefTransform:
  namespaced: true
  queries:
    Porta1: {tabularKeyColumn: "porta1"}


cells:
  porta1:
    dataRef: "porta1"
    thresholds:
      - {color: "green", level: 1}
      - {color: "red", level: 0}