anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"

datapoint: "last"

dataRefTransform:
  namespaced: false

cellIdPreamble: "cell-"

cells:
  porta1:
    dataRef: "Interface Gi0/1(PHFWNG01): Operational status"
    fillColor:
      thresholds:
        - {color: "green", level: 1}
        - {color: "red", level: 0}