dataRefTransform:
  namespaced: false

cellIdPreamble: "cell-"

cells:
  porta1:
    datapoint: "last"
    dataRef: "porta1"
    fillColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "green", level: -1}
    label:
      valueMap:
        0: "Down"
        1: "Up"